name: device_frame
description: Mockups for common devices.
version: 1.2.0
homepage: https://github.com/aloisdeniel/flutter_device_preview/device_frame

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  freezed_annotation: ^2.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  flutter_lints: ^5.0.0
  xml: ^6.5.0
  recase: ^4.1.0
